name: Publish release
on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
      dryrun:
        description: 'Dry run'
        default: false
        type: boolean
        required: false
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew
      - name: Extract variables
        run: |
          TAG_VERSION=$(echo "${{ github.ref_name }}" | sed 's/v//g')
          INPUT_VERSION=$(echo "${{  inputs.version }}" | sed 's/v//g')
          echo "tag: $TAG_VERSION input_version: $INPUT_VERSION"
          echo RELEASE_VERSION=${INPUT_VERSION:-${TAG_VERSION}} >> $GITHUB_ENV
          DRY_RUN_OPT=$( [ "${{ inputs.dryrun }}" == "true" ] && echo "--dry-run" || echo "" )
          echo "DRY_RUN_OPT=$DRY_RUN_OPT" >> $GITHUB_ENV
      - name: Show variables
        run: |
          echo "RELEASE_VERSION=${RELEASE_VERSION}"
          echo "DRY_RUN_OPT=${DRY_RUN_OPT}"
      - name: Build and test
        run: ./gradlew --no-daemon clean build
      - name: Deploy release
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
        run: .gradle -s --no-daemon -Pversion=${TAG_VERSION} publish closeAndReleaseStagingRepository ${DRY_RUN_OPT} -PgpgKey="${GPG_SECRET_KEY}" -PgpgPassphrase="${GPG_PASSPHRASE}" -PnexusUsername="${NEXUS_USERNAME}" -PnexusPassword="${NEXUS_PASSWORD}"